### ISSUE TITLE
Evaluation rule for "牧=A" is not implemented.

### ISSUE THREAD

**Issue by catupper** [catupper/777evaluator#1]
There is a strange rule on evaluating "牧=A". 
It must be evaluated into (7牧A7).

**Comment by catupper** [comment]
https://github.com/catupper/777evaluator/blob/56f93e301b2d300889e8cc7d07b1c3287c6f6a95/pages/index.vue#L30-L33

This part of the code are dealing with "牧=A" syntax, seems to be not working :( 

`Sentence::constructor` is called in a wrong way.

**Comment by nerikosans** [comment]
@catupper Opened a PR for this issue. Please check it out.
https://github.com/catupper/777evaluator/pull/2
